sudo: required
dist: trusty
language: node_js
node_js:
  - "6.9.0"
python:
  - "3.5"
cache:
  - pip
  - yarn
install:
  # Install any dependencies required for building your site here.
  # `awscli` is required for invalidation of CloudFront distributions.
  - pip install --user awscli
before_script:
  - yarn
script:
  # Build your site (e.g., HTML, CSS, JS) here.
  yarn run build
deploy:
  provider: s3
  access_key_id: AKIAJJGRGM2JGDDBAZ4Q
  secret_access_key:
    secure: jTjAzmGxCU0pSn5v4Gm5hHrYCAnbOCm12Hl5Fuxo4BWbJvOeqanBPptLmhYPNfYYvUJXmbBZi7jXukLD8Xeb9GCTEZCn4f62uwJqdYO3Tr7TrDSPQcjpd+XFaNner3DrYmkm9mk4k3OKDIVhPL5UJz3VFf8tO+VJtT0fFkICfOU=
  bucket: sendgrid-knowledge-center-staging
  acl: private
  on:
    repo: sendgrid/docs
    branch: a-new-hope-episode-iv
after_deploy:
  - aws configure set preview.cloudfront true
  - test $TRAVIS_BRANCH = "a-new-hope-episode-iv" && aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths "/*"
