sudo: required
dist: trusty
language: node_js
branches:
  only:
  - rc-master
  - rc-develop
node_js:
- 8.4.0
cache:
- pip
- yarn
install:
- pip install --user awscli
before_script:
- yarn
script: ./travis/build.sh
deploy:
  provider: script
  script: ./travis/build.sh
  skip_cleanup: true
  on:
    branch: rc-master
    branch: rc-develop
after_deploy:
- aws configure set preview.cloudfront true
- test $TRAVIS_BRANCH = "rc-master" && AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID_PROD --paths "/*"
- test $TRAVIS_BRANCH = "rc-develop" && AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DIST_ID_STAGE --paths "/*"