sudo: required
dist: trusty
language: node_js
branches:
  only:
  - a-new-hope-episode-iv
node_js:
- 8.4.0
cache:
- pip
- yarn
install:
- pip install --user awscli
before_script:
- yarn
- AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY aws s3 rm s3://sendgrid-knowledge-center-staging --recursive --region=us-east-1