sudo: required
dist: trusty
language: node_js
branches:
  only:
  - a-new-hope-episode-iv
node_js:
- 8.4.0
python:
- '3.5'
cache:
- pip
- yarn
install:
- pip install --user awscli
before_script:
- yarn
script: yarn run build
deploy:
  provider: s3
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  bucket: sendgrid-knowledge-center-staging
  skip_cleanup: true
  local_dir: public
  acl: public_read
  on:
    repo: sendgrid/docs
    branch: a-new-hope-episode-iv
after_deploy:
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY
  aws configure set preview.cloudfront true
  aws cloudfront create-invalidation --distribution-id $CLOUDFRONT_DISTRIBUTION_ID --paths /*
