sudo: required
dist: trusty
language: node_js
branches:
  only:
  - rc-master
  - rc-develop
node_js:
- 8.4.0
cache:
- pip
- yarn
install:
- pip install --user awscli
before_script:
- yarn
script: ./travis/build.sh
deploy:
  provider: script
  script: ./travis/deploy.sh
  skip_cleanup: true
  on:
    branch: rc-master
    branch: rc-develop
after_deploy: ./travis/after_deploy.sh